### ISSUE TITLE
Requirements project

### ISSUE THREAD

**Issue by MarcoAurelioAntonio** [MarcoAurelioAntonio/Recipe#8]
## Summary
Dear reviewer, We are 2 members for this team.
@paulsaenzsucre and @MarcoAurelioAntonio 

[This is our project link](https://github.com/users/MarcoAurelioAntonio/projects/6)

Thanks!!

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on but you are almost there!
🚦 __🏃 🏡 🏃‍♂️  🏚️ 🌴 🏫 

## Highlights 🎯  
🎲 Fair distribution of tasks!

## Required Changes ♻️
- [x] Cards for _Recipe details_ is missing! **Each** requirement from the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements) should have at least one corresponding card in the Kanban board. Let's add the missing card with the following criteria:
- **_Recipe details:_**
  * _Should display a toggle button that allows for a recipe to be made public or private._
  * _If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe._
  * _If the user is the owner of the recipe, should lead to the form that allows the user to add new food._

Cheers 👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-muhamad** [comment]
# Approved ✔
### Hi Team,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to close this issue and start working on the project :shipit: 

### GOOD LUCK 🤞 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
